### ISSUE TITLE
JSHint Warning

### ISSUE THREAD

**Issue by benmarten** [attila/grunt-critical-css#1]
First of all, thanks for this great project! Really appreciate the effort. It helps to optimise for Google Pagespeed Insights.

One little remark. I get a JSHint Warning for the actual task name: `critical_css`

Hence I suggest to rename it to `criticalCss`

My current workaround is this: `critical_css: { // jshint ignore: line`

**Comment by attila** [comment]
Thanks for the feedback. Regarding the JSHint warning, is this because you have the [camelcase](http://jshint.com/docs/options/#camelcase) option set? This seems deprecated as having underscores as variable names or object keys is perfectly valid. Please note that this project has its own, albeit quite minimalistic test suite which runs JSHint on itself too, see [this example](https://travis-ci.org/attila/grunt-critical-css/jobs/59858534). Hope that helps.

**Comment by benmarten** [comment]
great answer, didn't know that. thx for pointing that out...
